version: "3.7"

services:
  nodeapp:
    build: .
    ports:
      - "4000:4000"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin" # You should change this in production!
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - monitoring
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  monitoring:

volumes:
  grafana_data:
