global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: "webserver"
    static_configs:
      - targets: ["192.168.49.2:31110"] # Address of your webserver
